language: java
jdk:
  - oraclejdk8
  - openjdk7
  - openjdk6
script:
  - mvn clean compile test
after_success:
  - bash <(curl -s https://codecov.io/bash) 
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2b92385ecce89375e48
    on_success: change
    on_failure: always
    on_start: never
sudo: false
